[colors.primary]
background = "#24130e"
foreground = "#e8cf89"
[colors.cursor]
cursor = "#e8cf89"
text = "#24130e"
[colors.selection]
background = "#e8cf89"
text = "#24130e"
[colors.normal]
black = "#24130e"
red = "#b8150d"
green = "#9e7100"
yellow = "#db7a00"
blue = "#c48d49"
magenta = "#9c542d"
cyan = "#80854b"
white = "#e8cf89"
[colors.bright]
black = "#c48d49"
red = "#b8150d"
green = "#9e7100"
yellow = "#db7a00"
blue = "#c48d49"
magenta = "#9c542d"
cyan = "#80854b"
white = "#e8cf89"
