[colors.primary]
background = "#150d06"
foreground = "#e9d397"
[colors.cursor]
cursor = "#e9d397"
text = "#150d06"
[colors.selection]
background = "#e9d397"
text = "#150d06"
[colors.normal]
black = "#150d06"
red = "#b31c13"
green = "#855814"
yellow = "#c76800"
blue = "#b08548"
magenta = "#8a3820"
cyan = "#a83e00"
white = "#e9d397"
[colors.bright]
black = "#b08548"
red = "#b31c13"
green = "#855814"
yellow = "#c76800"
blue = "#b08548"
magenta = "#8a3820"
cyan = "#a83e00"
white = "#e9d397"
