[colors.primary]
background = "#221107"
foreground = "#f5efcd"
[colors.cursor]
cursor = "#f5efcd"
text = "#221107"
[colors.selection]
background = "#f5efcd"
text = "#221107"
[colors.normal]
black = "#221107"
red = "#990b3a"
green = "#cc561b"
yellow = "#e0a100"
blue = "#b98361"
magenta = "#ae3a34"
cyan = "#a16205"
white = "#f5efcd"
[colors.bright]
black = "#b98361"
red = "#990b3a"
green = "#cc561b"
yellow = "#e0a100"
blue = "#b98361"
magenta = "#ae3a34"
cyan = "#a16205"
white = "#f5efcd"
