[colors.primary]
background = "#382210"
foreground = "#e8d08e"

[colors.cursor]
cursor = "#e8d08e"
text = "#382210"

[colors.selection]
background = "#e8d08e"
text = "#382210"

[colors.normal]
black = "#382210"
red = "#ba1d14"
green = "#5a8241"
yellow = "#d97000"
blue = "#b08548"
magenta = "#b86a40"
cyan = "#bf4600"
white = "#e8d08e"

[colors.bright]
black = "#b08548"
red = "#ba1d14"
green = "#5a8241"
yellow = "#d97000"
blue = "#b08548"
magenta = "#b86a40"
cyan = "#bf4600"
white = "#e8d08e"
