require_relative('../libs/meta')

def puts_echo_sequence(hex_ansi, color)
  puts("echo -en \"\\\\e]P#{hex_ansi}#{$flamerial.get_color_hex(color)[1..]}\"")
end

puts("#!/usr/bin/env bash\n\n")
puts("[[ ${TERM} != \"linux\" ]] && exit\n\n")
puts_echo_sequence('0', :black)
puts_echo_sequence('1', :red)
puts_echo_sequence('2', :green)
puts_echo_sequence('3', :yellow)
puts_echo_sequence('4', :blue)
puts_echo_sequence('5', :magenta)
puts_echo_sequence('6', :cyan)
puts_echo_sequence('7', :white)
puts_echo_sequence('8', :light_black)
puts_echo_sequence('9', :red)
puts_echo_sequence('a', :green)
puts_echo_sequence('b', :yellow)
puts_echo_sequence('c', :blue)
puts_echo_sequence('d', :magenta)
puts_echo_sequence('e', :cyan)
puts_echo_sequence('f', :white)
