require_relative('../libs/metadata')

def puts_echo_sequence(hex_ansi, color)
  puts("echo -en \"\\\\e]P#{hex_ansi}#{color[1..]}\"")
end

puts('#!/usr/bin/env bash')
puts('[[ ${TERM} != \"linux\" ]] && exit')
puts_echo_sequence('0', $flamerial[:colors][:black])
puts_echo_sequence('1', $flamerial[:colors][:red])
puts_echo_sequence('2', $flamerial[:colors][:green])
puts_echo_sequence('3', $flamerial[:colors][:yellow])
puts_echo_sequence('4', $flamerial[:colors][:blue])
puts_echo_sequence('5', $flamerial[:colors][:magenta])
puts_echo_sequence('6', $flamerial[:colors][:cyan])
puts_echo_sequence('7', $flamerial[:colors][:white])
puts_echo_sequence('8', $flamerial[:colors][:light_black])
puts_echo_sequence('9', $flamerial[:colors][:red])
puts_echo_sequence('a', $flamerial[:colors][:green])
puts_echo_sequence('b', $flamerial[:colors][:yellow])
puts_echo_sequence('c', $flamerial[:colors][:blue])
puts_echo_sequence('d', $flamerial[:colors][:magenta])
puts_echo_sequence('e', $flamerial[:colors][:cyan])
puts_echo_sequence('f', $flamerial[:colors][:white])
