require_relative('../libs/meta')

puts(".*background: #{$flamerial.get_color_hex(:black)}")
puts(".*foreground: #{$flamerial.get_color_hex(:white)}")
puts(".*color0: #{$flamerial.get_color_hex(:black)}")
puts(".*color1: #{$flamerial.get_color_hex(:red)}")
puts(".*color2: #{$flamerial.get_color_hex(:green)}")
puts(".*color3: #{$flamerial.get_color_hex(:yellow)}")
puts(".*color4: #{$flamerial.get_color_hex(:blue)}")
puts(".*color5: #{$flamerial.get_color_hex(:magenta)}")
puts(".*color6: #{$flamerial.get_color_hex(:cyan)}")
puts(".*color7: #{$flamerial.get_color_hex(:white)}")
puts(".*color8: #{$flamerial.get_color_hex(:light_black)}")
puts(".*color9: #{$flamerial.get_color_hex(:red)}")
puts(".*color10: #{$flamerial.get_color_hex(:green)}")
puts(".*color11: #{$flamerial.get_color_hex(:yellow)}")
puts(".*color12: #{$flamerial.get_color_hex(:blue)}")
puts(".*color13: #{$flamerial.get_color_hex(:magenta)}")
puts(".*color14: #{$flamerial.get_color_hex(:cyan)}")
puts(".*color15: #{$flamerial.get_color_hex(:white)}")
