require_relative('../libs/metadata')

puts(".*background: #{$flamerial[:colors][:black]}")
puts(".*foreground: #{$flamerial[:colors][:white]}")
puts(".*color0: #{$flamerial[:colors][:black]}")
puts(".*color1: #{$flamerial[:colors][:red]}")
puts(".*color2: #{$flamerial[:colors][:green]}")
puts(".*color3: #{$flamerial[:colors][:yellow]}")
puts(".*color4: #{$flamerial[:colors][:blue]}")
puts(".*color5: #{$flamerial[:colors][:magenta]}")
puts(".*color6: #{$flamerial[:colors][:cyan]}")
puts(".*color7: #{$flamerial[:colors][:white]}")
puts(".*color8: #{$flamerial[:colors][:light_black]}")
puts(".*color9: #{$flamerial[:colors][:red]}")
puts(".*color10: #{$flamerial[:colors][:green]}")
puts(".*color11: #{$flamerial[:colors][:yellow]}")
puts(".*color12: #{$flamerial[:colors][:blue]}")
puts(".*color13: #{$flamerial[:colors][:magenta]}")
puts(".*color14: #{$flamerial[:colors][:cyan]}")
puts(".*color15: #{$flamerial[:colors][:white]}")
