[metadata]
name = "Flamerial Light"
author = "Sherman Rofeman"
origin_url = "https://github.com/skippyr/flamerial"
[colors]
background = "#f5f1e5"
foreground = "#704637"
cursor_bg = "#704637"
cursor_fg = "#f5f1e5"
selection_bg = "#704637"
selection_fg = "#f5f1e5"
ansi = [
    "#f5f1e5",
    "#b31c13",
    "#990101",
    "#c76800",
    "#b08548",
    "#8a3820",
    "#9c3900",
    "#704637"
]
brights = [
    "#b08548",
    "#b31c13",
    "#990101",
    "#c76800",
    "#b08548",
    "#8a3820",
    "#9c3900",
    "#704637"
]
