[metadata]
author = "Sherman Rofeman <skippyr.developer@icloud.com>"
name = "Flamerial"
origin_url = "https://github.com/skippyr/flamerial"

[colors]
background = "#150d06"
foreground = "#e9d397"
cursor_bg = "#e9d397"
cursor_border = "#e9d397"
cursor_fg = "#150d06"
selection_bg = "#e9d397"
selection_fg = "#150d06"
ansi = ["#150d06", "#b31c13", "#855814", "#c76800", "#b08548", "#8a3820",
        "#a83e00", "#e9d397"]
brights = ["#695f44", "#b31c13", "#855814", "#c76800", "#b08548", "#8a3820",
           "#a83e00", "#e9d397"]
