[metadata]
author = "Sherman Rofeman <skippyr.developer@gmail.com>"
name = "flamerial"
origin_url = "https://github.com/skippyr/flamerial"

[colors]
background = "#24130e"
foreground = "#e8cf89"
cursor_bg = "#e8cf89"
cursor_border = "#e8cf89"
cursor_fg = "#24130e"
selection_bg = "#e8cf89"
selection_fg = "#24130e"
ansi = ["#24130e", "#b8150d", "#9e7100", "#db7a00", "#c48d49", "#9c542d",
        "#80854b", "#e8cf89"]
brights = ["#c48d49", "#b8150d", "#9e7100", "#db7a00", "#c48d49", "#9c542d",
           "#80854b", "#e8cf89"]
