from flamerial import *

print('<table align="center">')
print('    <thead>')
print('        <tr>')
print('            <th>Preview</th>')
print('            <th>Name</th>')
print('            <th>HEX</th>')
print('            <th>RGB</th>')
print('        </tr>')
print('    </thead>')
print('    <tbody>')
for color in palette.all_colors:
    print('        <tr>')
    print(f'            <td><img alt="" src="{path.join(relative_colors_directory, color.image_file_name)}" /></td>')
    print(f'            <td>{color.name}</td>')
    print(f'            <td><code>{color.hex_string}</code></td>')
    print(f'            <td><code>{color.rgb_string}</code></td>')
    print('        </tr>')
print('    </tbody>')
print('</table>')
print('<p align="center"><strong>Caption:</strong> the colors that compose the theme palette.</p>')