## name: Flamerial
## author: Sherman Rofeman <skippyr.developer@icloud.com>
## license: BSD-3-Clause License

background               #000000
foreground               #CCB36E
active_tab_background    #CCB36E
active_tab_foreground    #000000
inactive_tab_background  #000000
inactive_tab_foreground  #CCB36E
cursor                   #CCB36E
cursor_text_color        #000000
selection_background     #CCB36E
selection_foreground     #000000
url_color                #7D0800
color0                   #000000
color1                   #7D0800
color2                   #4D4F2B
color3                   #C76800
color4                   #B08548
color5                   #663931
color6                   #913500
color7                   #CCB36E
color8                   #695F44
color9                   #7D0800
color10                  #4D4F2B
color11                  #C76800
color12                  #B08548
color13                  #663931
color14                  #913500
color15                  #CCB36E
